### ISSUE TITLE
Sextudy Group chapter 25 page order is wrong on cubari

### ISSUE THREAD

**Issue by Patriarch9307** [lunari17/luna-repo#1]
I couldn't find a way to contact you any other way so here goes. (idk how to send discord dm without being in a mutual server)

The latest chapter of Sextudy group (chapter 25) have a page out of order on your cubari gist. The current page 2 is supposed to be the last page as indicated by TBC text on it.

**Comment by lunari17** [comment]
Thanks for reporting the issue! It has been fixed now :D (It might take a while for cubari to reload the order correctly)
